---
# Staging Environment Inventory
# =====================================

all:
  vars:
    deploy_env: staging
    env_short: stg
    ansible_user: openclaw
    ansible_ssh_private_key_file: /home/openclaw/.ssh/id_ed25519
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    ansible_become: true
    ansible_become_method: sudo
    ansible_become_user: root

  children:
    localhost:
      hosts:
        127.0.0.1:
          ansible_connection: local
          ansible_become: false

    staging:
      hosts:
        ocl-worker-devops-002-stg:
          ansible_host: 34.101.152.17
          vm_role: devops
          vm_numeric_id: "002"